[package]
name = "cascade-print"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cascade"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
